apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 60m
  url: https://helm.github.io/examples
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-app
  namespace: sample-app
spec:
  interval: 5m
  dependsOn:
    - name: sample-app
      namespace: flux-system
  chart:
    spec:
      chart: hello-world
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: sample-app
        namespace: flux-system
