apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-app
  namespace: sample-app
spec:
  interval: 5m
  chart:
    spec:
      chart: hello-world
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: sample-app
        namespace: flux-system
  values:
    # Inline environment-specific values can be provided here
