apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: kube-system
spec:
  interval: 5m
  dependsOn:
    - name: prometheus
      namespace: flux-system
  chart:
    spec:
      chart: prometheus-adapter
      version: ''
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
