apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 60m
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m
  dependsOn:
    - name: podinfo
      namespace: flux-system
    - name: nginx-ingress
      namespace: kube-system
  chart:
    spec:
      chart: podinfo
      version: ''
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
