---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns-repo
  namespace: kube-system
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: ''
      sourceRef:
        kind: HelmRepository
        name: external-dns-repo
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-common-values
      valuesKey: common.values.yaml
