apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns.repo.yaml
  - external-dns.release.yaml

configMapGenerator:
  - name: external-dns-common-values
    files:
      - common.values.yaml
    options:
      disableNameSuffixHash: true
