apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 60m
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: podinfo
spec:
  interval: 5m
  dependsOn:
    - name: nginx-ingress
      namespace: flux-system
  chart:
    spec:
      chart: nginx-ingress
      version: ''
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
