apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: ''
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
